# Generated by Django 4.2.6 on 2023-11-06 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0011_director'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='director_email',
        ),
    ]
